# Generated by Django 4.2 on 2023-08-11 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_poster_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fallow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallowed', to=settings.AUTH_USER_MODEL)),
                ('fallowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallowing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
