# Generated by Django 4.2 on 2023-05-09 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlisting', to=settings.AUTH_USER_MODEL),
        ),
    ]
