# Generated by Django 4.2 on 2023-05-10 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='product',
        ),
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default='NULL', null=True, related_name='watchlisting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bids',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.listings'),
        ),
    ]
