# Generated by Django 4.2 on 2023-05-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_bids_product_alter_listings_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='product',
        ),
        migrations.AddField(
            model_name='bids',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
        ),
    ]
