# Generated by Django 4.2 on 2023-05-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_bids_product_bids_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='product',
        ),
        migrations.AlterField(
            model_name='listings',
            name='min_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.bids'),
        ),
    ]
