# Generated by Django 4.2 on 2023-05-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bids_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='min_bid',
            field=models.IntegerField(),
        ),
    ]
