# Generated by Django 4.2 on 2023-05-18 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bids_product_alter_listings_min_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_bid', to='auctions.listings'),
        ),
    ]
